### ISSUE TITLE
Add Blinka Stats/Metrics

### ISSUE THREAD

**Issue by sommersoft** [adafruit/adabot#119]
As mentioned in the 9 Dec 2019 weekly meeting, some stats & metrics are desired for things related to [Adafruit_Blinka](https://github.com/adafruit/Adafruit_Blinka).

PyPI download stats are already gathered daily [here](https://github.com/adafruit/adabot/blob/master/adabot/circuitpython_library_download_stats.py). Doesn't include data from `piwheels`; they still don't have a stats API available. Would be easy to get the PyPI stats into the meeting notes template; its basically a hardcoded one-liner.

What other sorts of information are wanted?

tagging: @makermelissa, @kattni, @tannewt 

_P.S. If this is a discussion better had on Discord voice, I'm fine with setting up a time for that. I just wanted to get an issue created here._

To-Do List
-----------

- [x] Gather Insights (issue/PR events, contribs, etc)
- [x] Blinka downloads (GitHub release & PyPI)
- [x] Count of supported boards

**Comment by makermelissa** [comment]
I'm not sure what the one-liner table includes, but I think we wanted to show stats on issues opened/closed, contributors, reviewers and similar stuff to the other tables. The download stats would be fine. We can improve it over time if we see things we want to add.

**Comment by tannewt** [comment]
Board count would be awesome to get in both the core and for Blinka too.

**Comment by makermelissa** [comment]
I just thought of something regarding this. We have the Blinka Repo, but we also have a few other related repos that Blinka relies on. Perhaps we can combine the stats together. The other repos that are used are Adafruit_Python_PlatformDetect and Adafruit_Python_PureIO.

**Comment by makermelissa** [comment]
Also, I noticed the number of supported boards seemed kind of high during the meeting. I looked at what you are doing and you're regexing the PlatformDetect to get all variations of defined boards. However, many of these are not supported and were only added for some reason before I ever worked on it. 

A more accurate way may be to look at the https://github.com/adafruit/circuitpython-org and just return the number of files in https://github.com/adafruit/circuitpython-org/tree/master/_blinka. This is very accurate since we will display all of these boards.
