### ISSUE TITLE
Check for setup.py.disabled as well as setup.py

### ISSUE THREAD

**Issue by dherrada** [adafruit/adabot#128]

**Comment by dherrada** [comment]
@siddacious I opened this a few days ago when I was working on the adabot pr. Is this something that would be a useful addition?

**Comment by siddacious** [comment]
I think for now this is covered by the check for repos missing setup.py. Renaming setup.py to setup.py.disabled is a hack to keep PyPi from being deployed. I'd rather be more intentional about it and have a clearer way to specify that a repo should not be deployed. The current behavior relies on some knowledge about the conditions under which a repo is deployed, and I think a better solution would be more clear. Once we figure out a better approach, we can add a check for that.
