### ISSUE TITLE
Can we use github actions "cron" to check for new pylint errors?

### ISSUE THREAD

**Issue by jepler** [adafruit/adabot#184]
> You can schedule a workflow to run at specific UTC times using POSIX cron syntax. Scheduled workflows run on the latest commit on the default or base branch. The shortest interval you can run scheduled workflows is once every 5 minutes.
> 
> This example triggers the workflow every 15 minutes:
> ```
> on:
>   schedule:
>     # * is a special character in YAML so you have to quote this string
>     - cron:  '*/15 * * * *'
> ```
> https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule

It seems like it should be adabot-patchable to add "run the workflow on the main branch daily/weekly, to make sure we promptly hear about pylint / other background changes that would affect releasability of bundle libraries.  Is this worth doing?

**Comment by sommersoft** [comment]
A cron'd workflow is definitely doable. I think a seperate workflow file would be a cleaner approach, but you could use the `github.event_name` context variable as the logic gate in `build.yml`.

However as I understand it, the only ways to discover the result of a cron'd check are:
  - Via the "workflow failed" emails from GitHub. I'm not even sure who these would be sent to. The librarians group? Ladyada? Kattni? A mixture based on each individual repo's settings?
  - Manually looking at the status of each repo.

I think it would be much more discoverable if it was integrated into a validator in `adabot/libs/circuitpython_library_validators.py`. The validator could clone the repo into a temp directory, run pylint, and report if there are errors (generically, not specific errors). This would put any failures onto `circuitpython.org/contributing` with the other library infrastructure issues. 
_This is a bit of a slippery slope though, as a lot of the existing validators that use the API could be changed to use the local clone (I over-analyze efficiency/pre-optimize too much 😄)._

The current [pylint-not-latest validator](https://github.com/adafruit/adabot/blob/b17b8fdb0854cc083e907f058efb130f95f963c7/adabot/lib/circuitpython_library_validators.py#L458) has become kind of useless since we switched to "rolling-release"; would be a good candidate to replace.
