### ISSUE TITLE
idea: add check that readthedocs are building

### ISSUE THREAD

**Issue by jepler** [adafruit/adabot#195]
It's easy for this to go unnoticed, and build failures don't always replicate locally.

**Comment by sommersoft** [comment]
This is already checked, in `validate_readthedocs`:
https://github.com/adafruit/adabot/blob/3b4020174d39abb4f9d9a69384cbe47bc04c8279/adabot/lib/circuitpython_library_validators.py#L816-L860

However, I will note that RTD's new v3 API provides some build info. I haven't fully determined if/how to get subproject build info; I'd need to setup an account and some builds since v3 requires authentication.

_Leaving issue open for further discussion. Is there any evidence the current validator isn't working properly? Do we want to change this issue to address a wider scope (transition to v3 API)?_

**Comment by jepler** [comment]
I don't have the specifics that prompted this request.  Let's just close it up, since it's supposed to be checked and I don't have any examples to the contrary.
