### ISSUE TITLE
Adabot not crediting author as a contributor on auto-release

### ISSUE THREAD

**Issue by makermelissa** [adafruit/adabot#82]
I noticed this today. I had wrote some updates (as well as did releases) on 3 display libraries. @siddacious reviewed all 3 of them. I noticed in the email it credits @siddacious and @adafruit-adabot, but not the author. It seems to me that she used to credit the library author as a contributor, but I could be wrong.

For instance, this is what I mean:
```
April 28, 2019 auto-release

Repository: adafruit/Adafruit_CircuitPython_Bundle · Tag: 20190428 · Commit: 37f8791 · Released by: adafruit-adabot

Updated libraries: ili9341, ssd1331, ssd1351

As always, thank you to all of our contributors: @siddacious, @adafruit-adabot
```

**Comment by sommersoft** [comment]
@makermelissa,

Just saw this, this morning. The commit message is built by reading `git` inspection commands, not the GitHub API. I believe that's why it pull the name of the "merger", not the author. I've started looking into how it be reflected better.

**Comment by makermelissa** [comment]
Ok, thanks.

**Comment by sommersoft** [comment]
So I finally carved out some time to dive into this today.

- First, a correction. The release notes do use the GitHub API and the commit sha to identify the author and commiter, for inclusion to the contributors. I previously pointed to the commit message, which doesn't use the API...but that's not the issue here.

- I walked the process by hand in a terminal. It all checks out in that sample size of 1. (Well, sample size of 2, if you count when I deleted it halfway through and started over.)

- I looked back to that day's adabot run, and the Travis log doesn't show any issues with anything. _I_ can't see anything that would fail silently in the code, but I guess its always a possibility. Maybe it was an issue with the Redis server? 🤷‍♂ 

- I scanned a number of releases since that April 28th release; all seem to be including the necessary individuals. 

I think this may have been a one-off. I'm cool with leaving the issue open, to continue monitoring the issue.
