### ISSUE TITLE
'validate_contents' Flags non-.py Files For Not Beginning w/ Sensor/Module Name

### ISSUE THREAD

**Issue by dherrada** [adafruit/adabot#87]
Repositories that have files in the examples folder that don't have the sensor/module name as a prefix and aren't .py files get added to list of modules missing module/sensor prefixes

_i moved the original title here - sommersoft_

**Comment by dherrada** [comment]
Sorry for such an ugly title

**Comment by sommersoft** [comment]
This should be an easy fix. Since the non-.py files aren't included in the bundle, I can support skipping them here. (The bundle was the main driver for ensuring each file had a proper prefix).

When (if?) we get [Folderize Example Bundles](https://github.com/adafruit/circuitpython-build-tools/issues/28) completed, this will probably still be unnecessary to check for non-.py.
